// Site Configuration
export const GET_GLOBAL_MATCHING_STATUS_START = "GET_GLOBAL_MATCHING_STATUS_START"
export const GET_GLOBAL_MATCHING_STATUS_SUCCESS = "GET_GLOBAL_MATCHING_STATUS_SUCCESS"
export const GET_GLOBAL_MATCHING_STATUS_FAILURE = "GET_GLOBAL_MATCHING_STATUS_FAILURE"

export const GET_ALL_SKILLSETS_START = "GET_ALL_SKILLSETS_START"
export const GET_ALL_SKILLSETS_SUCCESS = "GET_ALL_SKILLSETS_SUCCESS"
export const GET_ALL_SKILLSETS_FAILURE = "GET_ALL_SKILLSETS_FAILURE"

export const GET_ALL_PREFERENCES_START = "GET_ALL_PREFERENCES_START"
export const GET_ALL_PREFERENCES_SUCCESS = "GET_ALL_PREFERENCES_SUCCESS"
export const GET_ALL_PREFERENCES_FAILURE = "GET_ALL_PREFERENCES_FAILURE"

export const GET_ALL_PROGRAMS_START = "GET_ALL_PROGRAMS_START"
export const GET_ALL_PROGRAMS_SUCCESS = "GET_ALL_PROGRAMS_SUCCESS"
export const GET_ALL_PROGRAMS_FAILURE = "GET_ALL_PROGRAMS_FAILURE"

// Onboarding Flow
export const GET_OR_CREATE_USER_START = "GET_OR_CREATE_USER_START"
export const GET_OR_CREATE_USER_SUCCESS = "GET_OR_CREATE_USER_SUCCESS"
export const GET_OR_CREATE_USER_FAILURE = "GET_OR_CREATE_USER_FAILURE"

export const LOGOUT_USER_START = "LOGOUT_USER_START"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"

export const SIGNUP_CHECK_NEW_EMAIL_START = "SIGNUP_CHECK_NEW_EMAIL_START"
export const SIGNUP_CHECK_NEW_EMAIL_SUCCESS = "SIGNUP_CHECK_NEW_EMAIL_SUCCESS"
export const SIGNUP_CHECK_NEW_EMAIL_FAILURE = "SIGNUP_CHECK_NEW_EMAIL_FAILURE"

export const UPDATE_USER_PROFILE_START = "UPDATE_USER_PROFILE_START"
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS"
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE"

export const GET_CURRENT_USER_START = "GET_CURRENT_USER_START"
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS"
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE"

export const GET_CURRENT_USER_SKILLSETS_START = "GET_CURRENT_USER_SKILLSETS_START"
export const GET_CURRENT_USER_SKILLSETS_SUCCESS = "GET_CURRENT_USER_SKILLSETS_SUCCESS"
export const GET_CURRENT_USER_SKILLSETS_FAILURE = "GET_CURRENT_USER_SKILLSETS_FAILURE"

export const GET_ANOTHER_USER_SKILLSETS_START = "GET_ANOTHER_USER_SKILLSETS_START"
export const GET_ANOTHER_USER_SKILLSETS_SUCCESS = "GET_ANOTHER_USER_SKILLSETS_SUCCESS"
export const GET_ANOTHER_USER_SKILLSETS_FAILURE = "GET_ANOTHER_USER_SKILLSETS_FAILURE"

export const GET_CURRENT_USER_PREFERENCES_START = "GET_CURRENT_USER_PREFERENCES_START"
export const GET_CURRENT_USER_PREFERENCES_SUCCESS = "GET_CURRENT_USER_PREFERENCES_SUCCESS"
export const GET_CURRENT_USER_PREFERENCES_FAILURE = "GET_CURRENT_USER_PREFERENCES_FAILURE"

export const UPDATE_CURRENT_USER_SKILLSETS_START = "UPDATE_CURRENT_USER_SKILLSETS_START"
export const UPDATE_CURRENT_USER_SKILLSETS_SUCCESS = "UPDATE_CURRENT_USER_SKILLSETS_SUCCESS"
export const UPDATE_CURRENT_USER_SKILLSETS_FAILURE = "UPDATE_CURRENT_USER_SKILLSETS_FAILURE"

export const UPDATE_CURRENT_USER_PREFERENCES_START = "UPDATE_CURRENT_USER_PREFERENCES_START"
export const UPDATE_CURRENT_USER_PREFERENCES_SUCCESS = "UPDATE_CURRENT_USER_PREFERENCES_SUCCESS"
export const UPDATE_CURRENT_USER_PREFERENCES_FAILURE = "UPDATE_CURRENT_USER_PREFERENCES_FAILURE"

// Join Matching
export const JOIN_MATCHROUND_START = "JOIN_MATCHROUND_START"
export const JOIN_MATCHROUND_SUCCESS = "JOIN_MATCHROUND_SUCCESS"
export const JOIN_MATCHROUND_FAILURE = "JOIN_MATCHROUND_FAILURE"

export const LEAVE_MATCHROUND_START = "LEAVE_MATCHROUND_START"
export const LEAVE_MATCHROUND_SUCCESS = "LEAVE_MATCHROUND_SUCCESS"
export const LEAVE_MATCHROUND_FAILURE = "LEAVE_MATCHROUND_FAILURE"

// Post Matching
export const GET_GROUP_PROFILE_START = "GET_GROUP_PROFILE_START"
export const GET_GROUP_PROFILE_SUCCESS = "GET_GROUP_PROFILE_SUCCESS"
export const GET_GROUP_PROFILE_FAILURE = "GET_GROUP_PROFILE_FAILURE"

export const UPDATE_GROUP_COMMITMENT_START = "UPDATE_GROUP_COMMITMENT_START"
export const UPDATE_GROUP_COMMITMENT_SUCCESS = "UPDATE_GROUP_COMMITMENT_SUCCESS"
export const UPDATE_GROUP_COMMITMENT_FAILURE = "UPDATE_GROUP_COMMITMENT_FAILURE"

// untility
export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL"
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL"
export const SHOW_HOMEPAGE_WALKTHROUGH = "SHOW_HOMEPAGE_WALKTHROUGH"
export const SET_REDUCED_FOOTPRINT = "SET_REDUCED_FOOTPRINT"